### ISSUE TITLE
Link to "Analysis of the OpenSSL random API" broken

### ISSUE THREAD

**Issue by dgpv** [veorq/cryptocoding#7]
At least when opened in firefox, the link used for "Do *check the return values* of your RNG" `https://jbp.io/2014/01/16/openssl-rand-api/` gives 404, while `https://jbp.io/2014/01/16/openssl-rand-api` (without slash at the end) gives the needed page.

**Comment by veorq** [comment]
fixed in https://github.com/veorq/cryptocoding/commit/fb22bb500f4c3dae58bfd3aedb500cb58b07cf79, thanks!
