### ISSUE TITLE
Mistype: extra slash after /dev/urandom

### ISSUE THREAD

**Issue by dgpv** [veorq/cryptocoding#8]
In this sentence:
```
For example, on a Unix platform it would use `/dev/urandom/` and the RDRAND/RDSEED instructions, if available, among others.
```
The slash after urandom is an obvious mistype

**Comment by veorq** [comment]
fixed in https://github.com/veorq/cryptocoding/commit/fb22bb500f4c3dae58bfd3aedb500cb58b07cf79, thanks!
